version: "3"
services:
  web:
    container_name: docker-node
    restart: always
    build: .
    ports:
      - '80:5000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - '27018:27017'